### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by F3arM3** [EvilJagaGenius/jagoombacolor#6]
I really appreciate this emulator and am curious about some of the future updates.
will some of the updates include fixes such as the title screen of donkey kong country gbc not loading properly until it scrolls or is that just not possible with the hardware
And for games like animaniacs, bomberman collection, bomberman gb 1&2, bug's life, hercules, mulan, pocohauntus, hunchback of notre dam, toy story, fifa 98 & 2000, madden '97, nekketsu beach volley dayo kunio-kun, olympic summer games, poko-nyan yume no daibouken, pro mahjong kiwame, small soldiers, wario blast, and world cup '98 which all use the snes audio chip now have broken audio unless you select gameboy mode. So, will there be an option in the future to keep the super gameboy enhancements while also forcing gameboy audio or possibly some way to use the gba hardware in place of the snes audio chip?

**Comment by F3arM3** [comment]
nevermind on the dk one, I saw that you have been asked twice about that and mentioned you are fixing it

**Comment by EvilJagaGenius** [comment]
I'm not looking to add too many new features to the fork right now.  Part of this is due to the holidays, part of it is I've gotten all the games I'd like to play working and I have other projects I'd like to work on.  I do have a couple ideas - binding L to a speed-up function would make testing RPGs like Pokemon a lot easier.

DKC's title screen is very low-priority.  It's still readable, it just looks a little ugly pre-scroll.  I'm also not sure if I could write a fix for it without tanking the framerate.

I wasn't aware of the broken SGB audio - in fact I wasn't aware SGB games used the SNES sound chip at all?  I wonder how that works..?  I'm interested in fixing it, I like Goomba Color's SGB mode, but I need to do a little research.  No promises yet.

Anyways, don't expect anything major for a while.  I'm still enjoying the holidays over here and I hope yours are going well too!

**Comment by F3arM3** [comment]
ok, thank you for answering my question

**Comment by qamichelemassa5859** [comment]
> ok, thank you for answering my question

There has not be presented on an mGBA3DS Emulator as GoombaColor and JaGoombaColor emulators in O3DS System.
